[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "GenewebPy"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 79
