name: Mirror

on:
  push:
    branches:
    - 'main'

permissions:
  contents: write
  checks: write

env:
  MIRROR_URL: git@github.com:EpitechPGE45-2025/G-ING-900-PAR-9-1-legacy-31.git

jobs:
  push_to_mirror:
    if: success()
    runs-on: ubuntu-latest
    name: push_to_mirror
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
